export const ACTIONS = {
  REPORT_START: 'ACT_REPORT_START',
  STATUS: 'ACT_STATUS',
  REVIEWER: 'ACT_REVIEWER',
  HELP: 'ACT_HELP',
  CONTACT_YES: 'REPORT_CONTACT_YES',
  CONTACT_NO: 'REPORT_CONTACT_NO',
  REPORT_SUBMIT: 'REPORT_SUBMIT',
  REPORT_EDIT: 'REPORT_EDIT',
  REV_INBOX: 'REV_INBOX',
  REV_INPROG: 'REV_INPROG',
  REV_CLOSED: 'REV_CLOSED',
  REV_FIND: 'REV_FIND',
};

export const CALLBACK_PREFIXES = {
  ORG: 'ORG_',
  CAT: 'CAT_',
  REV_TAKE: 'REV_TAKE_',
  REV_REPLY: 'REV_REPLY_',
  REV_ASK: 'REV_ASK_',
  REV_CLOSE_CONF: 'REV_CLOSE_CONF_',
  REV_CLOSE_UNCONF: 'REV_CLOSE_UNCONF_',
  REV_REJECT: 'REV_REJECT_',
  CASE_REPLY: 'CASE_REPLY_',
  REV_ORG: 'REV_ORG_',
};
